### ISSUE TITLE
Better name for NodeValueFactory

### ISSUE THREAD

**Issue by remorhaz** [remorhaz/php-json-path#15]
Current class name `NodeValueFactory` may sound confusing for users without intimate knowledge of library internals. Maybe `DocumentFactory` will sound better? In fact, most users will use this class to instantiate JSON document before applying query to it.

**Comment by nicoseijas** [comment]
JSONDocumentFactory?

**Comment by remorhaz** [comment]
Thank you for your opinion! `JSON` is already part of namespace, and I thought that "document" in context of JSON-processing library is clearly a "JSON document" by default.

**Comment by remorhaz** [comment]
The class have moved to `remorhaz/php-json-data`, and so does the issue.
