### ISSUE TITLE
Support PHP 8.3

### ISSUE THREAD

**Issue by michaljusiega** [remorhaz/php-json-path#26]
Hi!

Can we add support for PHP 8.3?
In my project, I can't bump whole project with new version due to:

```
root@58265cb24d0b:/var/www# composer prohibits php 8.3
remorhaz/php-json-path v0.8.0 requires php (~8.0.0 || ~8.1.0 || ~8.2.0)
```

Thanks a lot!

**Comment by remorhaz** [comment]
Yep, I'm working on it right now, the dependencies are already updated. I will release a new version in a couple of days (maybe even tonight).

**Comment by michaljusiega** [comment]
Thank you!

**Comment by remorhaz** [comment]
Supported in 0.8.1.

**Comment by michaljusiega** [comment]
Thank you @remorhaz
